/*
• %c Prints a single character.
• %s Prints a string (as defined by the common C convention).
• %p The void * pointer argument has to be printed in hexadecimal format.
• %d Prints a decimal (base 10) number.
• %i Prints an integer in base 10.
• %u Prints an unsigned decimal (base 10) number.
• %x Prints a number in hexadecimal (base 16) lowercase format.
• %X Prints a number in hexadecimal (base 16) uppercase format.
• %% Prints a percent sign.

• # Prefix 0x to the value when used with the hexadec.conversion character x
• ' ' Print a space before a positive value not printed with the + flag.
• + Display '+'sign preceding positive values, '-'sign for negative values.
*/
//#include "ft_printf.h"
#include "ft_printf_bonus.h"
#include <limits.h>
#include <stdio.h>

int main()
{
	printf("\nspecificator %%\n");
	printf(". res for ft_printf for <%%>: <%i>\n", ft_printf("%%"));
	printf(". res for ft_printf for <100%%>: <%i>\n", ft_printf("100%%"));
	printf(". res for st_printf for <100%%>: <%i>\n", printf("100%%"));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("********************************************************************************************************\n\n");
	printf("flag <+>");
	printf("\nspecificator i\n");
	printf(". res for ft_printf for i = <-52> without flags: <%i>\n", ft_printf("%d", "hello"));
	printf(". res for st_printf for i = <-52> without flags: <%i>\n", printf("%d", "hello"));
	/*
	printf(". res for ft_printf for i = <-52> flag = <+i>: <%i>\n", ft_printf("%+i", -52));
	printf(". res for st_printf for i = <-52> flag = <+i>: <%i>\n", printf("%+i", -52));
	printf(". res for ft_printf for i = <-52> flag = <+5i>: <%i>\n", ft_printf("%+5i", -52));
	printf(". res for st_printf for i = <-52> flag = <+5i>: <%i>\n", printf("%+5i", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <INT_MIN> without flags: <%i>\n", ft_printf("%i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> without flags: <%i>\n", printf("%i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = <+i>: <%i>\n", ft_printf("%+i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = <+i>: <%i>\n", printf("%+i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = <+10i>: <%i>\n", ft_printf("%+10i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = <+10i>: <%i>\n", printf("%+10i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = <+20i>: <%i>\n", ft_printf("%+20i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = <+20i>: <%i>\n", printf("%+20i", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <0> without flags: <%i>\n", ft_printf("%i", 0));
	printf(". res for st_printf for i = <0> without flags: <%i>\n", printf("%i", 0));
	printf(". res for ft_printf for i = <0> flag = <+i>: <%i>\n", ft_printf("%+i", 0));
	printf(". res for st_printf for i = <0> flag = <+i>: <%i>\n", printf("%+i", 0));
	printf(". res for ft_printf for i = <0> flag = <+5i>: <%i>\n", ft_printf("%+5i", 0));
	printf(". res for st_printf for i = <0> flag = <+5i>: <%i>\n", printf("%+5i", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <52> without flags: <%i>\n", ft_printf("%i", 52));
	printf(". res for st_printf for i = <52> without flags: <%i>\n", printf("%i",+52));
	printf(". res for ft_printf for i = <52> flag = <+i>: <%i>\n", ft_printf("%+i", 52));
	printf(". res for st_printf for i = <52> flag = <+i>: <%i>\n", printf("%+i",+52));
	printf(". res for ft_printf for i = <52> flag = <+5i>: <%i>\n", ft_printf("%+5i", 52));
	printf(". res for st_printf for i = <52> flag = <+5i>: <%i>\n", printf("%+5i", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <INT_MAX> without flags: <%i>\n", ft_printf("%i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> without flags: <%i>\n", printf("%i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = <+i>: <%i>\n", ft_printf("%+i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = <+i>: <%i>\n", printf("%+i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = <+10i>: <%i>\n", ft_printf("%+10i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = <+10i>: <%i>\n", printf("%+10i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = <+20i>: <%i>\n", ft_printf("%+20i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = <+20i>: <%i>\n", printf("%+20i", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator d\n");
	printf(". res for ft_printf for d = <-52> without flags: <%i>\n", ft_printf("%d", -52));
	printf(". res for st_printf for d = <-52> without flags: <%i>\n", printf("%d", -52));
	printf(". res for ft_printf for d = <-52> flag = <+d>: <%i>\n", ft_printf("%+d", -52));
	printf(". res for st_printf for d = <-52> flag = <+d>: <%i>\n", printf("%+d", -52));
	printf(". res for ft_printf for d = <-52> flag = <+5d>: <%i>\n", ft_printf("%+5d", -52));
	printf(". res for st_printf for d = <-52> flag = <+5d>: <%i>\n", printf("%+5d", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <INT_MIN> without flags: <%i>\n", ft_printf("%d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> without flags: <%i>\n", printf("%d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = <+d>: <%i>\n", ft_printf("%+d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = <+d>: <%i>\n", printf("%+d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = <+10d>: <%i>\n", ft_printf("%+10d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = <+10d>: <%i>\n", printf("%+10d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = <+20d>: <%i>\n", ft_printf("%+20d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = <+20d>: <%i>\n", printf("%+20d", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <0> without flags: <%i>\n", ft_printf("%d", 0));
	printf(". res for st_printf for d = <0> without flags: <%i>\n", printf("%d", 0));
	printf(". res for ft_printf for d = <0> flag = <+d>: <%i>\n", ft_printf("%+d", 0));
	printf(". res for st_printf for d = <0> flag = <+d>: <%i>\n", printf("%+d", 0));
	printf(". res for ft_printf for d = <0> flag = <+5d>: <%i>\n", ft_printf("%+5d", 0));
	printf(". res for st_printf for d = <0> flag = <+5d>: <%i>\n", printf("%+5d", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <52> without flags: <%i>\n", ft_printf("%d", 52));
	printf(". res for st_printf for d = <52> without flags: <%i>\n", printf("%d",+52));
	printf(". res for ft_printf for d = <52> flag = <+d>: <%i>\n", ft_printf("%+d", 52));
	printf(". res for st_printf for d = <52> flag = <+d>: <%i>\n", printf("%+d",+52));
	printf(". res for ft_printf for d = <52> flag = <+5d>: <%i>\n", ft_printf("%+5d", 52));
	printf(". res for st_printf for d = <52> flag = <+5d>: <%i>\n", printf("%+5d", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <INT_MAX> without flags: <%i>\n", ft_printf("%d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> without flags: <%i>\n", printf("%d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = <+d>: <%i>\n", ft_printf("%+d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = <+d>: <%i>\n", printf("%+d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = <+10d>: <%i>\n", ft_printf("%+10d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = <+10d>: <%i>\n", printf("%+10d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = <+20d>: <%i>\n", ft_printf("%+20d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = <+20d>: <%i>\n", printf("%+20d", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator c\n");
	printf(". res for ft_printf for c = <A> without flags: <%i>\n", ft_printf("%c", 65));
	printf(". res for st_printf for c = <A> without flags: <%i>\n", printf("%c", 65));
	printf(". res for ft_printf for c = <A> flag = +1: <%i>\n", ft_printf("%+1c", 65));
	printf(". res for st_printf for c = <A> flag = +1: <%i>\n", printf("%+1c", 65));
	printf(". res for ft_printf for c = <A> flag = +10: <%i>\n", ft_printf("%+10c", 65));
	printf(". res for st_printf for c = <A> flag = +10: <%i>\n", printf("%+10c", 65));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator s\n");
	char *str = "hello";
	printf(". res for ft_printf for <hell0,42> without flags: <%i>\n", ft_printf("hell%i,%i", 0, 42));
	printf(". res for st_printf for <hell0,42> without flags: <%i>\n", printf("hell%i,%i", 0, 42));
	printf(". res for ft_printf for <hello,42> without flags: <%i>\n", ft_printf("%s%i", "hello", 42));
	printf(". res for st_printf for <hello,42> without flags: <%i>\n", printf("%s%i", "hello", 42));
	printf(". res for ft_printf for <hello,42> without flags: <%i>\n", ft_printf("%s%i", str, 42));
	printf(". res for st_printf for <hello,42> without flags: <%i>\n", printf("%s%i", str, 42));
	printf(". res for ft_printf for s = <65> flag = <+1s>: <%i>\n", ft_printf("%+1s", "65")); //flag
	printf(". res for st_printf for s = <65> flag = <+1s>: <%i>\n", printf("%+1s", "65"));
	printf(". res for ft_printf for s = <str> flag = <+1s>: <%i>\n", ft_printf("%+1s", str));
	printf(". res for st_printf for s = <str> flag = <+1s>: <%i>\n", printf("%+1s", str));
	printf(". res for ft_printf for s = <65> flag = <+15s>: <%i>\n", ft_printf("%+15s", "65"));
	printf(". res for st_printf for s = <65> flag = <+15s>: <%i>\n", printf("%+15s", "65"));
	printf(". res for ft_printf for s = <str> flag = <+15s>: <%i>\n", ft_printf("%+15s", str));
	printf(". res for st_printf for s = <str> flag = <+15s>: <%i>\n", printf("%+15s", str));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator p\n");
	printf(". res for ft_printf for p = <NULL> without flags: <%i>\n", ft_printf("%p", NULL));
	printf(". res for st_printf for p = <NULL> without flags: <%i>\n", printf("%p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = +p: <%i>\n", ft_printf("%+p", NULL));
	printf(". res for st_printf for p = <NULL> flag = +p: <%i>\n", printf("%+p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = +5p: <%i>\n", ft_printf("%+5p", NULL));
	printf(". res for st_printf for p = <NULL> flag = +5p: <%i>\n", printf("%+5p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = +10p: <%i>\n", ft_printf("%+10p", NULL));
	printf(". res for st_printf for p = <NULL> flag = +10p: <%i>\n", printf("%+10p", NULL));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for p = <str> without flags: <%i>\n", ft_printf("%p", str));
	printf(". res for st_printf for p = <str> without flags: <%i>\n", printf("%p", str));
	printf(". res for ft_printf for p = <str> flag = +p: <%i>\n", ft_printf("%+p", str));
	printf(". res for st_printf for p = <str> flag = +p: <%i>\n", printf("%+p", str));
	printf(". res for ft_printf for p = <str> flag = +10p: <%i>\n", ft_printf("%+10p", str));
	printf(". res for st_printf for p = <str> flag = +10p: <%i>\n", printf("%+10p", str));
	printf(". res for ft_printf for p = <str> flag = +20p: <%i>\n", ft_printf("%+20p", str));
	printf(". res for st_printf for p = <str> flag = +20p: <%i>\n", printf("%+20p", str));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for p = <5555> without flags: <%i>\n", ft_printf("%p", 5555));
	printf(". res for st_printf for p = <5555> without flags: <%i>\n", printf("%p", 5555));
	printf(". res for ft_printf for p = <5555> flag = +p: <%i>\n", ft_printf("%+p", 5555));
	printf(". res for st_printf for p = <5555> flag = +p: <%i>\n", printf("%+p", 5555));
	printf(". res for ft_printf for p = <5555> flag = +10p: <%i>\n", ft_printf("%+10p", 5555));
	printf(". res for st_printf for p = <5555> flag = +10p: <%i>\n", printf("%+10p", 5555));
	printf(". res for ft_printf for p = <5555> flag = +20p: <%i>\n", ft_printf("%+20p", 5555));
	printf(". res for st_printf for p = <5555> flag = +20p: <%i>\n", printf("%+20p", 5555));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator u\n");
	printf(". res for ft_printf for u = <-52> without flags: <%i>\n", ft_printf("%u", -52));
	printf(". res for st_printf for u = <-52> without flags: <%i>\n", printf("%u", -52));
	printf(". res for ft_printf for u = <-52> flag = +u: <%i>\n", ft_printf("%+u", -52));
	printf(". res for st_printf for u = <-52> flag = +u: <%i>\n", printf("%+u", -52));
	printf(". res for ft_printf for u = <-52> flag = +5u: <%i>\n", ft_printf("%+5u", -52));
	printf(". res for st_printf for u = <-52> flag = +5u: <%i>\n", printf("%+5u", -52));
	printf(". res for ft_printf for u = <-52> flag = +10u: <%i>\n", ft_printf("%+10u", -52));
	printf(". res for st_printf for u = <-52> flag = +10u: <%i>\n", printf("%+10u", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <INT_MIN> without flags: <%i>\n", ft_printf("%u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> without flags: <%i>\n", printf("%u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = +u: <%i>\n", ft_printf("%+u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = +u: <%i>\n", printf("%+u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = +10u: <%i>\n", ft_printf("%+10u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = +10u: <%i>\n", printf("%+10u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = +20u: <%i>\n", ft_printf("%+20u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = +20u: <%i>\n", printf("%+20u", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <0> without flags: <%i>\n", ft_printf("%u", 0));
	printf(". res for st_printf for u = <0> without flags: <%i>\n", printf("%u", 0));
	printf(". res for ft_printf for u = <0> flag = +u: <%i>\n", ft_printf("%+u", 0));
	printf(". res for st_printf for u = <0> flag = +u: <%i>\n", printf("%+u", 0));
	printf(". res for ft_printf for u = <0> flag = +5u: <%i>\n", ft_printf("%+5u", 0));
	printf(". res for st_printf for u = <0> flag = +5u: <%i>\n", printf("%+5u", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <52> without flags: <%i>\n", ft_printf("%u", 52));
	printf(". res for st_printf for u = <52> without flags: <%i>\n", printf("%u", 52));
	printf(". res for ft_printf for u = <52> flag = +u: <%i>\n", ft_printf("%+u", 52));
	printf(". res for st_printf for u = <52> flag = +u: <%i>\n", printf("%+u", 52));
	printf(". res for ft_printf for u = <52> flag = +10u: <%i>\n", ft_printf("%+10u", 52));
	printf(". res for st_printf for u = <52> flag = +10u: <%i>\n", printf("%+10u", 52));
	printf(". res for ft_printf for u = <52> flag = +20u: <%i>\n", ft_printf("%+20u", 52));
	printf(". res for st_printf for u = <52> flag = +20u: <%i>\n", printf("%+20u", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <INT_MAX> without flags: <%i>\n", ft_printf("%u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> without flags: <%i>\n", printf("%u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = +u: <%i>\n", ft_printf("%+u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = +u: <%i>\n", printf("%+u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = +10u: <%i>\n", ft_printf("%+10u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = +10u: <%i>\n", printf("%+10u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = +20u: <%i>\n", ft_printf("%+20u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = +20u: <%i>\n", printf("%+20u", INT_MAX));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <UINT_MAX> without flags: <%i>\n", ft_printf("%u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> without flags: <%i>\n", printf("%u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = +u: <%i>\n", ft_printf("%+u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = +u: <%i>\n", printf("%+u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = +10u: <%i>\n", ft_printf("%+10u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = +10u: <%i>\n", printf("%+10u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = +20u: <%i>\n", ft_printf("%+20u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = +20u: <%i>\n", printf("%+20u", UINT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("\nspecificator x\n");
	printf(". res for ft_printf for x = <-52> without flags: <%i>\n", ft_printf("%x", -52));
	printf(". res for st_printf for x = <-52> without flags: <%i>\n", printf("%x", -52));
	printf(". res for ft_printf for x = <-52> flag = +x: <%i>\n", ft_printf("%+x", -52));
	printf(". res for st_printf for x = <-52> flag = +x: <%i>\n", printf("%+x", -52));
	printf(". res for ft_printf for x = <-52> flag = +5x: <%i>\n", ft_printf("%+5x", -52));
	printf(". res for st_printf for x = <-52> flag = +5x: <%i>\n", printf("%+5x", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MIN> without flags: <%i>\n", ft_printf("%x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> without flags: <%i>\n", printf("%x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = +x: <%i>\n", ft_printf("%+x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = +x: <%i>\n", printf("%+x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = +10x: <%i>\n", ft_printf("%+10x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = +10x: <%i>\n", printf("%+10x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = +20x: <%i>\n", ft_printf("%+20x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = +20x: <%i>\n", printf("%+20x", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <0> without flags: <%i>\n", ft_printf("%x", 0));
	printf(". res for st_printf for x = <0> without flags: <%i>\n", printf("%x", 0));
	printf(". res for ft_printf for x = <0> flag = +x: <%i>\n", ft_printf("%+x", 0));
	printf(". res for st_printf for x = <0> flag = +x: <%i>\n", printf("%+x", 0));
	printf(". res for ft_printf for x = <0> flag = +5x: <%i>\n", ft_printf("%+5x", 0));
	printf(". res for st_printf for x = <0> flag = +5x: <%i>\n", printf("%+5x", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <52> without flags: <%i>\n", ft_printf("%x", 52));
	printf(". res for st_printf for x = <52> without flags: <%i>\n", printf("%x", 52));
	printf(". res for ft_printf for x = <52> flag = +x: <%i>\n", ft_printf("%+x", 52));
	printf(". res for st_printf for x = <52> flag = +x: <%i>\n", printf("%+x", 52));
	printf(". res for ft_printf for x = <52> flag = +10x: <%i>\n", ft_printf("%+10x", 52));
	printf(". res for st_printf for x = <52> flag = +10x: <%i>\n", printf("%+10x", 52));
	printf(". res for ft_printf for x = <52> flag = +20x: <%i>\n", ft_printf("%+20x", 52));
	printf(". res for st_printf for x = <52> flag = +20x: <%i>\n", printf("%+20x", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MAX> without flags: <%i>\n", ft_printf("%x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> without flags: <%i>\n", printf("%x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = +x: <%i>\n", ft_printf("%+x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = +x: <%i>\n", printf("%+x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = +10x: <%i>\n", ft_printf("%+10x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = +10x: <%i>\n", printf("%+10x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = +20x: <%i>\n", ft_printf("%+20x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = +20x: <%i>\n", printf("%+20x", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("\nspecificator X\n");
	printf(". res for ft_printf for X = <-52> without flags: <%i>\n", ft_printf("%X", -52));
	printf(". res for st_printf for X = <-52> without flags: <%i>\n", printf("%X", -52));
	printf(". res for ft_printf for X = <-52> flag = +X: <%i>\n", ft_printf("%+X", -52));
	printf(". res for st_printf for X = <-52> flag = +X: <%i>\n", printf("%+X", -52));
	printf(". res for ft_printf for X = <-52> flag = +10X: <%i>\n", ft_printf("%+10X", -52));
	printf(". res for st_printf for X = <-52> flag = +10X: <%i>\n", printf("%+10X", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <INT_MIN> without flags: <%i>\n", ft_printf("%X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> without flags: <%i>\n", printf("%X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = +X: <%i>\n", ft_printf("%+X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = +X: <%i>\n", printf("%+X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = +10X: <%i>\n", ft_printf("%+10X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = +10X: <%i>\n", printf("%+10X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = +20X: <%i>\n", ft_printf("%+20X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = +20X: <%i>\n", printf("%+20X", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <0> without flags: <%i>\n", ft_printf("%X", 0));
	printf(". res for st_printf for X = <0> without flags: <%i>\n", printf("%X", 0));
	printf(". res for ft_printf for X = <0> flag = +X: <%i>\n", ft_printf("%+X", 0));
	printf(". res for st_printf for X = <0> flag = +X: <%i>\n", printf("%+X", 0));
	printf(". res for ft_printf for X = <0> flag = +5X: <%i>\n", ft_printf("%+5X", 0));
	printf(". res for st_printf for X = <0> flag = +5X: <%i>\n", printf("%+5X", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <52> without flags: <%i>\n", ft_printf("%X", 52));
	printf(". res for st_printf for X = <52> without flags: <%i>\n", printf("%X", 52));
	printf(". res for ft_printf for X = <52> flag = +X: <%i>\n", ft_printf("%+X", 52));
	printf(". res for st_printf for X = <52> flag = +X: <%i>\n", printf("%+X", 52));
	printf(". res for ft_printf for X = <52> flag = +10X: <%i>\n", ft_printf("%+10X", 52));
	printf(". res for st_printf for X = <52> flag = +10X: <%i>\n", printf("%+10X", 52));
	printf(". res for ft_printf for X = <52> flag = +20X: <%i>\n", ft_printf("%+20X", 52));
	printf(". res for st_printf for X = <52> flag = +20X: <%i>\n", printf("%+20X", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MAX> without flags: <%i>\n", ft_printf("%X", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> without flags: <%i>\n", printf("%X", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = +X: <%i>\n", ft_printf("%+X", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = +X: <%i>\n", printf("%+X", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = +10X: <%i>\n", ft_printf("%+10X", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = +10X: <%i>\n", printf("%+10X", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = +20X: <%i>\n", ft_printf("%+20X", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = +20X: <%i>\n", printf("%+20X", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("********************************************************************************************************\n\n");
	printf("flag < >");
	printf("\nspecificator i\n");
	printf(". res for ft_printf for i = <-52> without flags: <%i>\n", ft_printf("%i", -52));
	printf(". res for st_printf for i = <-52> without flags: <%i>\n", printf("%i", -52));
	printf(". res for ft_printf for i = <-52> flag = < i>: <%i>\n", ft_printf("% i", -52));
	printf(". res for st_printf for i = <-52> flag = < i>: <%i>\n", printf("% i", -52));
	printf(". res for ft_printf for i = <-52> flag = < 5i>: <%i>\n", ft_printf("% 5i", -52));
	printf(". res for st_printf for i = <-52> flag = < 5i>: <%i>\n", printf("% 5i", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <INT_MIN> without flags: <%i>\n", ft_printf("%i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> without flags: <%i>\n", printf("%i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = < i>: <%i>\n", ft_printf("% i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = < i>: <%i>\n", printf("% i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = < 10i>: <%i>\n", ft_printf("% 10i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = < 10i>: <%i>\n", printf("% 10i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = < 20i>: <%i>\n", ft_printf("% 20i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = < 20i>: <%i>\n", printf("% 20i", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <0> without flags: <%i>\n", ft_printf("%i", 0));
	printf(". res for st_printf for i = <0> without flags: <%i>\n", printf("%i", 0));
	printf(". res for ft_printf for i = <0> flag = < i>: <%i>\n", ft_printf("% i", 0));
	printf(". res for st_printf for i = <0> flag = < i>: <%i>\n", printf("% i", 0));
	printf(". res for ft_printf for i = <0> flag = < 5i>: <%i>\n", ft_printf("% 5i", 0));
	printf(". res for st_printf for i = <0> flag = < 5i>: <%i>\n", printf("% 5i", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <52> without flags: <%i>\n", ft_printf("%i", 52));
	printf(". res for st_printf for i = <52> without flags: <%i>\n", printf("%i", 52));
	printf(". res for ft_printf for i = <52> flag = < i>: <%i>\n", ft_printf("% i", 52));
	printf(". res for st_printf for i = <52> flag = < i>: <%i>\n", printf("% i", 52));
	printf(". res for ft_printf for i = <52> flag = < 5i>: <%i>\n", ft_printf("% 5i", 52));
	printf(". res for st_printf for i = <52> flag = < 5i>: <%i>\n", printf("% 5i", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <INT_MAX> without flags: <%i>\n", ft_printf("%i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> without flags: <%i>\n", printf("%i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = < i>: <%i>\n", ft_printf("% i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = < i>: <%i>\n", printf("% i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = < 10i>: <%i>\n", ft_printf("% 10i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = < 10i>: <%i>\n", printf("% 10i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = < 20i>: <%i>\n", ft_printf("% 20i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = < 20i>: <%i>\n", printf("% 20i", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator d\n");
	printf(". res for ft_printf for d = <-52> without flags: <%i>\n", ft_printf("%d", -52));
	printf(". res for st_printf for d = <-52> without flags: <%i>\n", printf("%d", -52));
	printf(". res for ft_printf for d = <-52> flag = < d>: <%i>\n", ft_printf("% d", -52));
	printf(". res for st_printf for d = <-52> flag = < d>: <%i>\n", printf("% d", -52));
	printf(". res for ft_printf for d = <-52> flag = < 5d>: <%i>\n", ft_printf("% 5d", -52));
	printf(". res for st_printf for d = <-52> flag = < 5d>: <%i>\n", printf("% 5d", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <INT_MIN> without flags: <%i>\n", ft_printf("%d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> without flags: <%i>\n", printf("%d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = < d>: <%i>\n", ft_printf("% d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = < d>: <%i>\n", printf("% d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = < 10d>: <%i>\n", ft_printf("% 10d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = < 10d>: <%i>\n", printf("% 10d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = < 20d>: <%i>\n", ft_printf("% 20d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = < 20d>: <%i>\n", printf("% 20d", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <0> without flags: <%i>\n", ft_printf("%d", 0));
	printf(". res for st_printf for d = <0> without flags: <%i>\n", printf("%d", 0));
	printf(". res for ft_printf for d = <0> flag = < d>: <%i>\n", ft_printf("% d", 0));
	printf(". res for st_printf for d = <0> flag = < d>: <%i>\n", printf("% d", 0));
	printf(". res for ft_printf for d = <0> flag = < 5d>: <%i>\n", ft_printf("% 5d", 0));
	printf(". res for st_printf for d = <0> flag = < 5d>: <%i>\n", printf("% 5d", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <52> without flags: <%i>\n", ft_printf("%d", 52));
	printf(". res for st_printf for d = <52> without flags: <%i>\n", printf("%d",+52));
	printf(". res for ft_printf for d = <52> flag = < d>: <%i>\n", ft_printf("% d", 52));
	printf(". res for st_printf for d = <52> flag = < d>: <%i>\n", printf("% d", 52));
	printf(". res for ft_printf for d = <52> flag = < 5d>: <%i>\n", ft_printf("% 5d", 52));
	printf(". res for st_printf for d = <52> flag = < 5d>: <%i>\n", printf("% 5d", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <INT_MAX> without flags: <%i>\n", ft_printf("%d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> without flags: <%i>\n", printf("%d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = < d>: <%i>\n", ft_printf("% d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = < d>: <%i>\n", printf("% d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = < 10d>: <%i>\n", ft_printf("% 10d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = < 10d>: <%i>\n", printf("% 10d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = < 20d>: <%i>\n", ft_printf("% 20d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = < 20d>: <%i>\n", printf("% 20d", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator c\n");
	printf(". res for ft_printf for c = <A> without flags: <%i>\n", ft_printf("%c", 65));
	printf(". res for st_printf for c = <A> without flags: <%i>\n", printf("%c", 65));
	printf(". res for ft_printf for c = <A> flag = < 1>: <%i>\n", ft_printf("% 1c", 65));
	printf(". res for st_printf for c = <A> flag = < 1>: <%i>\n", printf("% 1c", 65));
	printf(". res for ft_printf for c = <A> flag = < 1>: <%i>\n", ft_printf("% 10c", 65));
	printf(". res for st_printf for c = <A> flag = < 1>: <%i>\n", printf("% 10c", 65));
	printf(". res for ft_printf for c = <A> flag = < 15>: <%i>\n", ft_printf("% 15c", 65));
	printf(". res for st_printf for c = <A> flag = < 15>: <%i>\n", printf("% 15c", 65));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator s\n");
	printf(". res for ft_printf for s = <65> without flags: <%i>\n", ft_printf("%s", "65"));
	printf(". res for st_printf for s = <65> without flags: <%i>\n", printf("%s", "65"));
	printf(". res for ft_printf for s = <65> flag = < 3s>: <%i>\n", ft_printf("% 3s", "65"));
	printf(". res for st_printf for s = <65> flag = < 3s>: <%i>\n", printf("% 3s", "65"));
	printf(". res for ft_printf for s = <str> flag = < 3s>: <%i>\n", ft_printf("% 3s", str));
	printf(". res for st_printf for s = <str> flag = < 3s>: <%i>\n", printf("% 3s", str));
	printf(". res for ft_printf for s = <65> flag = < 15s>: <%i>\n", ft_printf("% 15s", "65"));
	printf(". res for st_printf for s = <65> flag = < 15s>: <%i>\n", printf("% 15s", "65"));
	printf(". res for ft_printf for s = <str> flag = < 15s>: <%i>\n", ft_printf("% 15s", str));
	printf(". res for st_printf for s = <str> flag = < 15s>: <%i>\n", printf("% 15s", str));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator p\n");
	printf(". res for ft_printf for p = <NULL> without flags: <%i>\n", ft_printf("%p", NULL));
	printf(". res for st_printf for p = <NULL> without flags: <%i>\n", printf("%p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = < p>: <%i>\n", ft_printf("% p", NULL));
	printf(". res for st_printf for p = <NULL> flag = < p>: <%i>\n", printf("% p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = < 5p>: <%i>\n", ft_printf("% 5p", NULL));
	printf(". res for st_printf for p = <NULL> flag = < 5p>: <%i>\n", printf("% 5p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = < 10p>: <%i>\n", ft_printf("% 10p", NULL));
	printf(". res for st_printf for p = <NULL> flag = < 10p>: <%i>\n", printf("% 10p", NULL));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for p = <str> without flags: <%i>\n", ft_printf("%p", str));
	printf(". res for st_printf for p = <str> without flags: <%i>\n", printf("%p", str));
	printf(". res for ft_printf for p = <str> flag = < p>: <%i>\n", ft_printf("% p", str));
	printf(". res for st_printf for p = <str> flag = < p>: <%i>\n", printf("% p", str));
	printf(". res for ft_printf for p = <str> flag = < 10p>: <%i>\n", ft_printf("% 10p", str));
	printf(". res for st_printf for p = <str> flag = < 10p>: <%i>\n", printf("% 10p", str));
	printf(". res for ft_printf for p = <str> flag = < 20p>: <%i>\n", ft_printf("% 20p", str));
	printf(". res for st_printf for p = <str> flag = < 20p>: <%i>\n", printf("% 20p", str));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for p = <5555> without flags: <%i>\n", ft_printf("%p", 5555));
	printf(". res for st_printf for p = <5555> without flags: <%i>\n", printf("%p", 5555));
	printf(". res for ft_printf for p = <5555> flag = < p>: <%i>\n", ft_printf("% p", 5555));
	printf(". res for st_printf for p = <5555> flag = < p>: <%i>\n", printf("% p", 5555));
	printf(". res for ft_printf for p = <5555> flag = < 5p>: <%i>\n", ft_printf("% 5p", 5555));
	printf(". res for st_printf for p = <5555> flag = < 5p>: <%i>\n", printf("% 5p", 5555));
	printf(". res for ft_printf for p = <5555> flag = < 10p>: <%i>\n", ft_printf("% 10p", 5555));
	printf(". res for st_printf for p = <5555> flag = < 10p>: <%i>\n", printf("% 10p", 5555));
	printf(". res for ft_printf for p = <5555> flag = < 20p>: <%i>\n", ft_printf("% 20p", 5555));
	printf(". res for st_printf for p = <5555> flag = < 20p>: <%i>\n", printf("% 20p", 5555));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator u\n");
	printf(". res for ft_printf for u = <-52> without flags: <%i>\n", ft_printf("%u", -52));
	printf(". res for st_printf for u = <-52> without flags: <%i>\n", printf("%u", -52));
	printf(". res for ft_printf for u = <-52> flag = < u>: <%i>\n", ft_printf("% u", -52));
	printf(". res for st_printf for u = <-52> flag = < u>: <%i>\n", printf("% u", -52));
	printf(". res for ft_printf for u = <-52> flag = < 5u>: <%i>\n", ft_printf("% 5u", -52));
	printf(". res for st_printf for u = <-52> flag = < 5u>: <%i>\n", printf("% 5u", -52));
	printf(". res for ft_printf for u = <-52> flag = < 10u>: <%i>\n", ft_printf("% 10u", -52));
	printf(". res for st_printf for u = <-52> flag = < 10u>: <%i>\n", printf("% 10u", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <INT_MIN> without flags: <%i>\n", ft_printf("%u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> without flags: <%i>\n", printf("%u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = < u>: <%i>\n", ft_printf("% u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = < u>: <%i>\n", printf("% u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = < 10u>: <%i>\n", ft_printf("% 10u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = < 10u>: <%i>\n", printf("% 10u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = < 20u>: <%i>\n", ft_printf("% 20u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = < 20u>: <%i>\n", printf("% 20u", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <0> without flags: <%i>\n", ft_printf("%u", 0));
	printf(". res for st_printf for u = <0> without flags: <%i>\n", printf("%u", 0));
	printf(". res for ft_printf for u = <0> flag = < u>: <%i>\n", ft_printf("% u", 0));
	printf(". res for st_printf for u = <0> flag = < u>: <%i>\n", printf("% u", 0));
	printf(". res for ft_printf for u = <0> flag = < 5u>: <%i>\n", ft_printf("% 5u", 0));
	printf(". res for st_printf for u = <0> flag = < 5u>: <%i>\n", printf("% 5u", 0));
	printf(". res for ft_printf for u = <0> flag = < 10u>: <%i>\n", ft_printf("% 10u", 0));
	printf(". res for st_printf for u = <0> flag = < 10u>: <%i>\n", printf("% 10u", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <52> without flags: <%i>\n", ft_printf("%u", 52));
	printf(". res for st_printf for u = <52> without flags: <%i>\n", printf("%u", 52));
	printf(". res for ft_printf for u = <52> flag = < u>: <%i>\n", ft_printf("% u", 52));
	printf(". res for st_printf for u = <52> flag = < u>: <%i>\n", printf("% u", 52));
	printf(". res for ft_printf for u = <52> flag = < 10u>: <%i>\n", ft_printf("% 10u", 52));
	printf(". res for st_printf for u = <52> flag = < 10u>: <%i>\n", printf("% 10u", 52));
	printf(". res for ft_printf for u = <52> flag = < 20u>: <%i>\n", ft_printf("% 20u", 52));
	printf(". res for st_printf for u = <52> flag = < 20u>: <%i>\n", printf("% 20u", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <INT_MAX> without flags: <%i>\n", ft_printf("%u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> without flags: <%i>\n", printf("%u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = < u>: <%i>\n", ft_printf("% u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = < u>: <%i>\n", printf("% u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = < 10u>: <%i>\n", ft_printf("% 10u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = < 10u>: <%i>\n", printf("% 10u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = < 20u>: <%i>\n", ft_printf("% 20u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = < 20u>: <%i>\n", printf("% 20u", INT_MAX));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <UINT_MAX> without flags: <%i>\n", ft_printf("%u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> without flags: <%i>\n", printf("%u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = < u>: <%i>\n", ft_printf("% u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = < u>: <%i>\n", printf("% u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = < 10u>: <%i>\n", ft_printf("% 10u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = < 10u>: <%i>\n", printf("% 10u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = < 20u>: <%i>\n", ft_printf("% 20u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = < 20u>: <%i>\n", printf("% 20u", UINT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("\nspecificator x\n");
	printf(". res for ft_printf for x = <-52> without flags: <%i>\n", ft_printf("%x", -52));
	printf(". res for st_printf for x = <-52> without flags: <%i>\n", printf("%x", -52));
	printf(". res for ft_printf for x = <-52> flag = < x>: <%i>\n", ft_printf("% x", -52));
	printf(". res for st_printf for x = <-52> flag = < x>: <%i>\n", printf("% x", -52));
	printf(". res for ft_printf for x = <-52> flag = < 5x>: <%i>\n", ft_printf("% 5x", -52));
	printf(". res for st_printf for x = <-52> flag = < 5x>: <%i>\n", printf("% 5x", -52));
	printf(". res for ft_printf for x = <-52> flag = < 10x>: <%i>\n", ft_printf("% 10x", -52));
	printf(". res for st_printf for x = <-52> flag = < 10x>: <%i>\n", printf("% 10x", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MIN> without flags: <%i>\n", ft_printf("%x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> without flags: <%i>\n", printf("%x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = < x>: <%i>\n", ft_printf("% x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = < x>: <%i>\n", printf("% x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = < 10x>: <%i>\n", ft_printf("% 10x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = < 10x>: <%i>\n", printf("% 10x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = < 20x>: <%i>\n", ft_printf("% 20x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = < 20x>: <%i>\n", printf("% 20x", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <0> without flags: <%i>\n", ft_printf("%x", 0));
	printf(". res for st_printf for x = <0> without flags: <%i>\n", printf("%x", 0));
	printf(". res for ft_printf for x = <0> flag = < x>: <%i>\n", ft_printf("% x", 0));
	printf(". res for st_printf for x = <0> flag = < x>: <%i>\n", printf("% x", 0));
	printf(". res for ft_printf for x = <0> flag = < 5x>: <%i>\n", ft_printf("% 5x", 0));
	printf(". res for st_printf for x = <0> flag = < 5x>: <%i>\n", printf("% 5x", 0));
	printf(". res for ft_printf for x = <0> flag = < 10x>: <%i>\n", ft_printf("% 10x", 0));
	printf(". res for st_printf for x = <0> flag = < 10x>: <%i>\n", printf("% 10x", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <52> without flags: <%i>\n", ft_printf("%x", 52));
	printf(". res for st_printf for x = <52> without flags: <%i>\n", printf("%x", 52));
	printf(". res for ft_printf for x = <52> flag = < x>: <%i>\n", ft_printf("% x", 52));
	printf(". res for st_printf for x = <52> flag = < x>: <%i>\n", printf("% x", 52));
	printf(". res for ft_printf for x = <52> flag = < 10x>: <%i>\n", ft_printf("% 10x", 52));
	printf(". res for st_printf for x = <52> flag = < 10x>: <%i>\n", printf("% 10x", 52));
	printf(". res for ft_printf for x = <52> flag = < 20x>: <%i>\n", ft_printf("% 20x", 52));
	printf(". res for st_printf for x = <52> flag = < 20x>: <%i>\n", printf("% 20x", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MAX> without flags: <%i>\n", ft_printf("%x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> without flags: <%i>\n", printf("%x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = < x>: <%i>\n", ft_printf("% x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = < x>: <%i>\n", printf("% x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = < 10x>: <%i>\n", ft_printf("% 10x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = < 10x>: <%i>\n", printf("% 10x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = < 20x>: <%i>\n", ft_printf("% 20x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = < 20x>: <%i>\n", printf("% 20x", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("\nspecificator X\n");
	printf(". res for ft_printf for X = <-52> without flags: <%i>\n", ft_printf("%X", -52));
	printf(". res for st_printf for X = <-52> without flags: <%i>\n", printf("%X", -52));
	printf(". res for ft_printf for X = <-52> flag = < X>: <%i>\n", ft_printf("% X", -52));
	printf(". res for st_printf for X = <-52> flag = < X>: <%i>\n", printf("% X", -52));
	printf(". res for ft_printf for X = <-52> flag = < 10X>: <%i>\n", ft_printf("% 10X", -52));
	printf(". res for st_printf for X = <-52> flag = < 10x>: <%i>\n", printf("% 10X", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <INT_MIN> without flags: <%i>\n", ft_printf("%X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> without flags: <%i>\n", printf("%X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = < X>: <%i>\n", ft_printf("% X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = < X>: <%i>\n", printf("% X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = < 10X>: <%i>\n", ft_printf("% 10X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = < 10X>: <%i>\n", printf("% 10X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = < 20X>: <%i>\n", ft_printf("% 20X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = < 20X>: <%i>\n", printf("% 20X", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <0> without flags: <%i>\n", ft_printf("%X", 0));
	printf(". res for st_printf for X = <0> without flags: <%i>\n", printf("%X", 0));
	printf(". res for ft_printf for X = <0> flag = < X>: <%i>\n", ft_printf("% X", 0));
	printf(". res for st_printf for X = <0> flag = < X>: <%i>\n", printf("% X", 0));
	printf(". res for ft_printf for X = <0> flag = < 5X>: <%i>\n", ft_printf("% 5X", 0));
	printf(". res for st_printf for X = <0> flag = < 5X>: <%i>\n", printf("% 5X", 0));
	printf(". res for ft_printf for X = <0> flag = < 10X>: <%i>\n", ft_printf("% 10X", 0));
	printf(". res for st_printf for X = <0> flag = < 10X>: <%i>\n", printf("% 10X", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <52> without flags: <%i>\n", ft_printf("%X", 52));
	printf(". res for st_printf for X = <52> without flags: <%i>\n", printf("%X", 52));
	printf(". res for ft_printf for X = <52> flag = < X>: <%i>\n", ft_printf("% X", 52));
	printf(". res for st_printf for X = <52> flag = < X>: <%i>\n", printf("% X", 52));
	printf(". res for ft_printf for X = <52> flag = < 10X>: <%i>\n", ft_printf("% 10X", 52));
	printf(". res for st_printf for X = <52> flag = < 10X>: <%i>\n", printf("% 10X", 52));
	printf(". res for ft_printf for X = <52> flag = < 20X>: <%i>\n", ft_printf("% 20X", 52));
	printf(". res for st_printf for X = <52> flag = < 20X>: <%i>\n", printf("% 20X", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <INT_MAX> without flags: <%i>\n", ft_printf("%X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> without flags: <%i>\n", printf("%X", INT_MAX));
	printf(". res for ft_printf for X = <INT_MAX> flag = < X>: <%i>\n", ft_printf("% X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> flag = < X>: <%i>\n", printf("% X", INT_MAX));
	printf(". res for ft_printf for X = <INT_MAX> flag = < 10X>: <%i>\n", ft_printf("% 10X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> flag = < 10X>: <%i>\n", printf("% 10X", INT_MAX));
	printf(". res for ft_printf for X = <INT_MAX> flag = < 20X>: <%i>\n", ft_printf("% 20X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> flag = < 20X>: <%i>\n", printf("% 20X", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("********************************************************************************************************\n\n");
	printf("flag <#>");
	printf("\nspecificator i\n");
	printf(". res for ft_printf for i = <-52> without flags: <%i>\n", ft_printf("%i", -52));
	printf(". res for st_printf for i = <-52> without flags: <%i>\n", printf("%i", -52));
	printf(". res for ft_printf for i = <-52> flag = <#i>: <%i>\n", ft_printf("%#i", -52));
	printf(". res for st_printf for i = <-52> flag = <#i>: <%i>\n", printf("%#i", -52));
	printf(". res for ft_printf for i = <-52> flag = <#5i>: <%i>\n", ft_printf("%#5i", -52));
	printf(". res for st_printf for i = <-52> flag = <#5i>: <%i>\n", printf("%#5i", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <INT_MIN> without flags: <%i>\n", ft_printf("%i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> without flags: <%i>\n", printf("%i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = <#i>: <%i>\n", ft_printf("%#i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = <#i>: <%i>\n", printf("%#i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = <#10i>: <%i>\n", ft_printf("%#10i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = <#10i>: <%i>\n", printf("%#10i", INT_MIN));
	printf(". res for ft_printf for i = <INT_MIN> flag = <#20i>: <%i>\n", ft_printf("%#20i", INT_MIN));
	printf(". res for st_printf for i = <INT_MIN> flag = <#20i>: <%i>\n", printf("%#20i", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <0> without flags: <%i>\n", ft_printf("%i", 0));
	printf(". res for st_printf for i = <0> without flags: <%i>\n", printf("%i", 0));
	printf(". res for ft_printf for i = <0> flag = <#i>: <%i>\n", ft_printf("%#i", 0));
	printf(". res for st_printf for i = <0> flag = <#i>: <%i>\n", printf("%#i", 0));
	printf(". res for ft_printf for i = <0> flag = <#5i>: <%i>\n", ft_printf("%#5i", 0));
	printf(". res for st_printf for i = <0> flag = <#5i>: <%i>\n", printf("%#5i", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <52> without flags: <%i>\n", ft_printf("%i", 52));
	printf(". res for st_printf for i = <52> without flags: <%i>\n", printf("%i", 52));
	printf(". res for ft_printf for i = <52> flag = <#i>: <%i>\n", ft_printf("%#i", 52));
	printf(". res for st_printf for i = <52> flag = <#i>: <%i>\n", printf("%#i", 52));
	printf(". res for ft_printf for i = <52> flag = <#5i>: <%i>\n", ft_printf("%#5i", 52));
	printf(". res for st_printf for i = <52> flag = <#5i>: <%i>\n", printf("%#5i", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for i = <INT_MAX> without flags: <%i>\n", ft_printf("%i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> without flags: <%i>\n", printf("%i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = <#i>: <%i>\n", ft_printf("%#i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = <#i>: <%i>\n", printf("%#i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = <#10i>: <%i>\n", ft_printf("%#10i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = <#10i>: <%i>\n", printf("%#10i", INT_MAX));
	printf(". res for ft_printf for i = <INT_MAX> flag = <#20i>: <%i>\n", ft_printf("%#20i", INT_MAX));
	printf(". res for st_printf for i = <INT_MAX> flag = <#20i>: <%i>\n", printf("%#20i", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator d\n");
	printf(". res for ft_printf for d = <-52> without flags: <%i>\n", ft_printf("%d", -52));
	printf(". res for st_printf for d = <-52> without flags: <%i>\n", printf("%d", -52));
	printf(". res for ft_printf for d = <-52> flag = <#d>: <%i>\n", ft_printf("%#d", -52));
	printf(". res for st_printf for d = <-52> flag = <#d>: <%i>\n", printf("%#d", -52));
	printf(". res for ft_printf for d = <-52> flag = <#5d>: <%i>\n", ft_printf("%#5d", -52));
	printf(". res for st_printf for d = <-52> flag = <#5d>: <%i>\n", printf("%#5d", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <INT_MIN> without flags: <%i>\n", ft_printf("%d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> without flags: <%i>\n", printf("%d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = <#d>: <%i>\n", ft_printf("%#d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = <#d>: <%i>\n", printf("%#d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = <#10d>: <%i>\n", ft_printf("%#10d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = <#10d>: <%i>\n", printf("%#10d", INT_MIN));
	printf(". res for ft_printf for d = <INT_MIN> flag = <#20d>: <%i>\n", ft_printf("%#20d", INT_MIN));
	printf(". res for st_printf for d = <INT_MIN> flag = <#20d>: <%i>\n", printf("%#20d", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <0> without flags: <%i>\n", ft_printf("%d", 0));
	printf(". res for st_printf for d = <0> without flags: <%i>\n", printf("%d", 0));
	printf(". res for ft_printf for d = <0> flag = <#d>: <%i>\n", ft_printf("%#d", 0));
	printf(". res for st_printf for d = <0> flag = <#d>: <%i>\n", printf("%#d", 0));
	printf(". res for ft_printf for d = <0> flag = <#5d>: <%i>\n", ft_printf("%#5d", 0));
	printf(". res for st_printf for d = <0> flag = <#5d>: <%i>\n", printf("%#5d", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <52> without flags: <%i>\n", ft_printf("%d", 52));
	printf(". res for st_printf for d = <52> without flags: <%i>\n", printf("%d",+52));
	printf(". res for ft_printf for d = <52> flag = <#d>: <%i>\n", ft_printf("%#d", 52));
	printf(". res for st_printf for d = <52> flag = <#d>: <%i>\n", printf("%#d", 52));
	printf(". res for ft_printf for d = <52> flag = <#5d>: <%i>\n", ft_printf("%#5d", 52));
	printf(". res for st_printf for d = <52> flag = <#5d>: <%i>\n", printf("%#5d", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for d = <INT_MAX> without flags: <%i>\n", ft_printf("%d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> without flags: <%i>\n", printf("%d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = <#d>: <%i>\n", ft_printf("%#d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = <#d>: <%i>\n", printf("%#d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = <#10d>: <%i>\n", ft_printf("%#10d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = <#10d>: <%i>\n", printf("%#10d", INT_MAX));
	printf(". res for ft_printf for d = <INT_MAX> flag = <#20d>: <%i>\n", ft_printf("%#20d", INT_MAX));
	printf(". res for st_printf for d = <INT_MAX> flag = <#20d>: <%i>\n", printf("%#20d", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator c\n");
	printf(". res for ft_printf for c = <A> without flags: <%i>\n", ft_printf("%c", 65));
	printf(". res for st_printf for c = <A> without flags: <%i>\n", printf("%c", 65));
	printf(". res for ft_printf for c = <A> flag = <#>: <%i>\n", ft_printf("%#c", 65));
	printf(". res for st_printf for c = <A> flag = <#>: <%i>\n", printf("%#c", 65));
	printf(". res for ft_printf for c = <A> flag = <#5>: <%i>\n", ft_printf("%#5c", 65));
	printf(". res for st_printf for c = <A> flag = <#5>: <%i>\n", printf("%#5c", 65));
	printf(". res for ft_printf for c = <A> flag = <#10>: <%i>\n", ft_printf("%#10c", 65));
	printf(". res for st_printf for c = <A> flag = <#10>: <%i>\n", printf("%#10c", 65));
	printf(". res for ft_printf for c = <A> flag = <#15>: <%i>\n", ft_printf("%#15c", 65));
	printf(". res for st_printf for c = <A> flag = <#15>: <%i>\n", printf("%#15c", 65));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator s\n");
	printf(". res for ft_printf for s = <65> flag = <#3s>: <%i>\n", ft_printf("%#3s", "65"));
	printf(". res for st_printf for s = <65> flag = <#3s>: <%i>\n", printf("%#3s", "65"));
	printf(". res for ft_printf for s = <str> flag = <#3s>: <%i>\n", ft_printf("%#3s", str));
	printf(". res for st_printf for s = <str> flag = <#3s>: <%i>\n", printf("%#3s", str));
	printf(". res for ft_printf for s = <65> flag = <#15s>: <%i>\n", ft_printf("%#15s", "65"));
	printf(". res for st_printf for s = <65> flag = <#15s>: <%i>\n", printf("%#15s", "65"));
	printf(". res for ft_printf for s = <str> flag = <#15s>: <%i>\n", ft_printf("%#15s", str));
	printf(". res for st_printf for s = <str> flag = <#15s>: <%i>\n", printf("%#15s", str));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator p\n");
	printf(". res for ft_printf for p = <NULL> without flags: <%i>\n", ft_printf("%p", NULL));
	printf(". res for st_printf for p = <NULL> without flags: <%i>\n", printf("%p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = <#p>: <%i>\n", ft_printf("%#p", NULL));
	printf(". res for st_printf for p = <NULL> flag = <#p>: <%i>\n", printf("%#p", NULL));
	printf(". res for ft_printf for p = <NULL> flag = <#10p>: <%i>\n", ft_printf("%#10p", NULL));
	printf(". res for st_printf for p = <NULL> flag = <#10p>: <%i>\n", printf("%#10p", NULL));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for p = <str> without flags: <%i>\n", ft_printf("%p", str));
	printf(". res for st_printf for p = <str> without flags: <%i>\n", printf("%p", str));
	printf(". res for ft_printf for p = <str> flag = <#p>: <%i>\n", ft_printf("%#p", str));
	printf(". res for st_printf for p = <str> flag = <#p>: <%i>\n", printf("%#p", str));
	printf(". res for ft_printf for p = <str> flag = <#10p>: <%i>\n", ft_printf("%#10p", str));
	printf(". res for st_printf for p = <str> flag = <#10p>: <%i>\n", printf("%#10p", str));
	printf(". res for ft_printf for p = <str> flag = <#20p>: <%i>\n", ft_printf("%#20p", str));
	printf(". res for st_printf for p = <str> flag = <#20p>: <%i>\n", printf("%#20p", str));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for p = <5555> without flags: <%i>\n", ft_printf("%p", 5555));
	printf(". res for st_printf for p = <5555> without flags: <%i>\n", printf("%p", 5555));
	printf(". res for ft_printf for p = <5555> flag = <#p>: <%i>\n", ft_printf("%#p", 5555));
	printf(". res for st_printf for p = <5555> flag = <#p>: <%i>\n", printf("%#p", 5555));
	printf(". res for ft_printf for p = <5555> flag = <#10p>: <%i>\n", ft_printf("%#10p", 5555));
	printf(". res for st_printf for p = <5555> flag = <#10p>: <%i>\n", printf("%#10p", 5555));
	printf(". res for ft_printf for p = <5555> flag = <#20p>: <%i>\n", ft_printf("%#20p", 5555));
	printf(". res for st_printf for p = <5555> flag = <#20p>: <%i>\n", printf("%#20p", 5555));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n\n");
	printf("\nspecificator u\n");
	printf(". res for ft_printf for u = <-52> without flags: <%i>\n", ft_printf("%u", -52));
	printf(". res for st_printf for u = <-52> without flags: <%i>\n", printf("%u", -52));
	printf(". res for ft_printf for u = <-52> flag = <#u>: <%i>\n", ft_printf("%#u", -52));
	printf(". res for st_printf for u = <-52> flag = <#u>: <%i>\n", printf("%#u", -52));
	printf(". res for ft_printf for u = <-52> flag = <#10u>: <%i>\n", ft_printf("%#10u", -52));
	printf(". res for st_printf for u = <-52> flag = <#10u>: <%i>\n", printf("%#10u", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <INT_MIN> without flags: <%i>\n", ft_printf("%u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> without flags: <%i>\n", printf("%u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = <#u>: <%i>\n", ft_printf("%#u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = <#u>: <%i>\n", printf("%#u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = <#10u>: <%i>\n", ft_printf("%#10u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = <#10u>: <%i>\n", printf("%#10u", INT_MIN));
	printf(". res for ft_printf for u = <INT_MIN> flag = <#20u>: <%i>\n", ft_printf("%#20u", INT_MIN));
	printf(". res for st_printf for u = <INT_MIN> flag = <#20u>: <%i>\n", printf("%#20u", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <0> without flags: <%i>\n", ft_printf("%u", 0));
	printf(". res for st_printf for u = <0> without flags: <%i>\n", printf("%u", 0));
	printf(". res for ft_printf for u = <0> flag = <#u>: <%i>\n", ft_printf("%#u", 0));
	printf(". res for st_printf for u = <0> flag = <#u>: <%i>\n", printf("%#u", 0));
	printf(". res for ft_printf for u = <0> flag = <#10u>: <%i>\n", ft_printf("%#10u", 0));
	printf(". res for st_printf for u = <0> flag = <#10u>: <%i>\n", printf("%#10u", 0));
	printf(". res for ft_printf for u = <0> flag = <#20u>: <%i>\n", ft_printf("%#20u", 0));
	printf(". res for st_printf for u = <0> flag = <#20u>: <%i>\n", printf("%#20u", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <52> without flags: <%i>\n", ft_printf("%u", 52));
	printf(". res for st_printf for u = <52> without flags: <%i>\n", printf("%u", 52));
	printf(". res for ft_printf for u = <52> flag = <#u>: <%i>\n", ft_printf("%#u", 52));
	printf(". res for st_printf for u = <52> flag = <#u>: <%i>\n", printf("%#u", 52));
	printf(". res for ft_printf for u = <52> flag = <#10u>: <%i>\n", ft_printf("%#10u", 52));
	printf(". res for st_printf for u = <52> flag = <#10u>: <%i>\n", printf("%#10u", 52));
	printf(". res for ft_printf for u = <52> flag = <#20u>: <%i>\n", ft_printf("%#20u", 52));
	printf(". res for st_printf for u = <52> flag = <#20u>: <%i>\n", printf("%#20u", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <INT_MAX> without flags: <%i>\n", ft_printf("%u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> without flags: <%i>\n", printf("%u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = <#u>: <%i>\n", ft_printf("%#u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = <#u>: <%i>\n", printf("%#u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = <#10u>: <%i>\n", ft_printf("%#10u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = <#10u>: <%i>\n", printf("%#10u", INT_MAX));
	printf(". res for ft_printf for u = <INT_MAX> flag = <#20u>: <%i>\n", ft_printf("%#20u", INT_MAX));
	printf(". res for st_printf for u = <INT_MAX> flag = <#20u>: <%i>\n", printf("%#20u", INT_MAX));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for u = <UINT_MAX> without flags: <%i>\n", ft_printf("%u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> without flags: <%i>\n", printf("%u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = <#u>: <%i>\n", ft_printf("%#u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = <#u>: <%i>\n", printf("%#u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = <#10u>: <%i>\n", ft_printf("%#10u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = <#10u>: <%i>\n", printf("%#10u", UINT_MAX));
	printf(". res for ft_printf for u = <UINT_MAX> flag = <#20u>: <%i>\n", ft_printf("%#20u", UINT_MAX));
	printf(". res for st_printf for u = <UINT_MAX> flag = <#20u>: <%i>\n", printf("%#20u", UINT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("\nspecificator x\n");
	printf(". res for ft_printf for x = <-52> without flags: <%i>\n", ft_printf("%x", -52));
	printf(". res for st_printf for x = <-52> without flags: <%i>\n", printf("%x", -52));
	printf(". res for ft_printf for x = <-52> flag = <#x>: <%i>\n", ft_printf("%#x", -52));
	printf(". res for st_printf for x = <-52> flag = <#x>: <%i>\n", printf("%#x", -52));
	printf(". res for ft_printf for x = <-52> flag = <#10x>: <%i>\n", ft_printf("%#10x", -52));
	printf(". res for st_printf for x = <-52> flag = <#10x>: <%i>\n", printf("%#10x", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MIN> without flags: <%i>\n", ft_printf("%x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> without flags: <%i>\n", printf("%x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = <#x>: <%i>\n", ft_printf("%#x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = <#x>: <%i>\n", printf("%#x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = <#10x>: <%i>\n", ft_printf("%#10x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = <#10x>: <%i>\n", printf("%#10x", INT_MIN));
	printf(". res for ft_printf for x = <INT_MIN> flag = <#20x>: <%i>\n", ft_printf("%#20x", INT_MIN));
	printf(". res for st_printf for x = <INT_MIN> flag = <#20x>: <%i>\n", printf("%#20x", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <0> without flags: <%i>\n", ft_printf("%x", 0));
	printf(". res for st_printf for x = <0> without flags: <%i>\n", printf("%x", 0));
	printf(". res for ft_printf for x = <0> flag = <#x>: <%i>\n", ft_printf("%#x", 0));
	printf(". res for st_printf for x = <0> flag = <#x>: <%i>\n", printf("%#x", 0));
	printf(". res for ft_printf for x = <0> flag = <#10x>: <%i>\n", ft_printf("%#10x", 0));
	printf(". res for st_printf for x = <0> flag = <#10x>: <%i>\n", printf("%#10x", 0));
	printf(". res for ft_printf for x = <0> flag = <#20x>: <%i>\n", ft_printf("%#20x", 0));
	printf(". res for st_printf for x = <0> flag = <#20x>: <%i>\n", printf("%#20x", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <52> without flags: <%i>\n", ft_printf("%x", 52));
	printf(". res for st_printf for x = <52> without flags: <%i>\n", printf("%x", 52));
	printf(". res for ft_printf for x = <52> flag = <#x>: <%i>\n", ft_printf("%#x", 52));
	printf(". res for st_printf for x = <52> flag = <#x>: <%i>\n", printf("%#x", 52));
	printf(". res for ft_printf for x = <52> flag = <#10x>: <%i>\n", ft_printf("%#10x", 52));
	printf(". res for st_printf for x = <52> flag = <#10x>: <%i>\n", printf("%#10x", 52));
	printf(". res for ft_printf for x = <52> flag = <#20x>: <%i>\n", ft_printf("%#20x", 52));
	printf(". res for st_printf for x = <52> flag = <#20x>: <%i>\n", printf("%#20x", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for x = <INT_MAX> without flags: <%i>\n", ft_printf("%x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> without flags: <%i>\n", printf("%x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = <#x>: <%i>\n", ft_printf("%#x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = <#x>: <%i>\n", printf("%#x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = <#10x>: <%i>\n", ft_printf("%#10x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = <#10x>: <%i>\n", printf("%#10x", INT_MAX));
	printf(". res for ft_printf for x = <INT_MAX> flag = <#20x>: <%i>\n", ft_printf("%#20x", INT_MAX));
	printf(". res for st_printf for x = <INT_MAX> flag = <#20x>: <%i>\n", printf("%#20x", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("\nspecificator X\n");
	printf(". res for ft_printf for X = <-52> without flags: <%i>\n", ft_printf("%X", -52));
	printf(". res for st_printf for X = <-52> without flags: <%i>\n", printf("%X", -52));
	printf(". res for ft_printf for X = <-52> flag = <#X>: <%i>\n", ft_printf("%#X", -52));
	printf(". res for st_printf for X = <-52> flag = <#X>: <%i>\n", printf("%#X", -52));
	printf(". res for ft_printf for X = <-52> flag = <#10X>: <%i>\n", ft_printf("%#10X", -52));
	printf(". res for st_printf for X = <-52> flag = <#10x>: <%i>\n", printf("%#10X", -52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <INT_MIN> without flags: <%i>\n", ft_printf("%X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> without flags: <%i>\n", printf("%X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = <#X>: <%i>\n", ft_printf("%#X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = <#X>: <%i>\n", printf("%#X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = <#10X>: <%i>\n", ft_printf("%#10X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = <#10X>: <%i>\n", printf("%#10X", INT_MIN));
	printf(". res for ft_printf for X = <INT_MIN> flag = <#20X>: <%i>\n", ft_printf("%#20X", INT_MIN));
	printf(". res for st_printf for X = <INT_MIN> flag = <#20X>: <%i>\n", printf("%#20X", INT_MIN));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <0> without flags: <%i>\n", ft_printf("%X", 0));
	printf(". res for st_printf for X = <0> without flags: <%i>\n", printf("%X", 0));
	printf(". res for ft_printf for X = <0> flag = <#X>: <%i>\n", ft_printf("%#X", 0));
	printf(". res for st_printf for X = <0> flag = <#X>: <%i>\n", printf("%#X", 0));
	printf(". res for ft_printf for X = <0> flag = <#10X>: <%i>\n", ft_printf("%#10X", 0));
	printf(". res for st_printf for X = <0> flag = <#10X>: <%i>\n", printf("%#10X", 0));
	printf(". res for ft_printf for X = <0> flag = <#20X>: <%i>\n", ft_printf("%#20X", 0));
	printf(". res for st_printf for X = <0> flag = <#20X>: <%i>\n", printf("%#20X", 0));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <52> without flags: <%i>\n", ft_printf("%X", 52));
	printf(". res for st_printf for X = <52> without flags: <%i>\n", printf("%X", 52));
	printf(". res for ft_printf for X = <52> flag = <#X>: <%i>\n", ft_printf("%#X", 52));
	printf(". res for st_printf for X = <52> flag = <#X>: <%i>\n", printf("%#X", 52));
	printf(". res for ft_printf for X = <52> flag = <#10X>: <%i>\n", ft_printf("%#10X", 52));
	printf(". res for st_printf for X = <52> flag = <#10X>: <%i>\n", printf("%#10X", 52));
	printf(". res for ft_printf for X = <52> flag = <#20X>: <%i>\n", ft_printf("%#20X", 52));
	printf(". res for st_printf for X = <52> flag = <#20X>: <%i>\n", printf("%#20X", 52));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for X = <INT_MAX> without flags: <%i>\n", ft_printf("%X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> without flags: <%i>\n", printf("%X", INT_MAX));
	printf(". res for ft_printf for X = <INT_MAX> flag = <#X>: <%i>\n", ft_printf("%#X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> flag = <#X>: <%i>\n", printf("%#X", INT_MAX));
	printf(". res for ft_printf for X = <INT_MAX> flag = <#10X>: <%i>\n", ft_printf("%#10X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> flag = <#10X>: <%i>\n", printf("%#10X", INT_MAX));
	printf(". res for ft_printf for X = <INT_MAX> flag = <#20X>: <%i>\n", ft_printf("%#20X", INT_MAX));
	printf(". res for st_printf for X = <INT_MAX> flag = <#20X>: <%i>\n", printf("%#20X", INT_MAX));
	printf("________________________________________________________________________________________________________\n");
	printf("********************************************************************************************************\n");
	printf("********************************************************************************************************\n\n");
	printf("\ncombination of '+' and ' '\n");
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+ 3s>, <+ 2s>, <+ p>, <+ 4d>): <%i>\n", ft_printf("%+ 3s%+ 2s%+ p.(%+ 4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+ 3s>, <+ 2s>, <+ p>, <+ 4d>): <%i>\n", printf("%+ 3s%+ 2s%+ p.(%+ 4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < +3s>, < +2s>, < +p>, < +4d>): <%i>\n", ft_printf("% +3s% +2s% +p.(% +4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < +3s>, < +2s>, < +p>, < +4d>): <%i>\n", printf("% +3s% +2s% +p.(% +4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+ 3s>, <+ 8s>, <+ p>, <+ 4d>): <%i>\n", ft_printf("%+ 3s%+ 8s%+ p.(%+ 4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+ 3s>, <+ 8s>, <+ p>, <+ 4d>): <%i>\n", printf("%+ 3s%+ 8s%+ p.(%+ 4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < +3s>, < +8s>, < +p>, < +4d>): <%i>\n", ft_printf("% +3s% +8s% +p.(% +4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < +3s>, < +8s>, < +p>, < +4d>): <%i>\n", printf("% +3s% +8s% +p.(% +4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <+ 3s>, <+ 2s>, <+ p>, <+ 4d>): <%i>\n", ft_printf("%+ 3s%+ 2s%+ p.(%+ 4d)", "65", str, str, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <+ 3s>, <+ 2s>, <+ p>, <+ 4d>): <%i>\n", printf("%+ 3s%+ 2s%+ p.(%+ 4d)", "65", str, str, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: < +3s>, < +2s>, < +p>, < +4d>): <%i>\n", ft_printf("% +3s% +2s% +p.(% +4d)", "65", str, str, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: < +3s>, < +2s>, < +p>, < +4d>): <%i>\n", printf("% +3s% +2s% +p.(% +4d)", "65", str, str, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <+ 3s>, <+ 20s>, <+ p>, <+ 4d>): <%i>\n", ft_printf("%+ 3s%+ 20s%+ p.(%+ 4d)", "65", str, str, 55));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <+ 3s>, <+ 20s>, <+ p>, <+ 4d>): <%i>\n", printf("%+ 3s%+ 20s%+ p.(%+ 4d)", "65", str, str, 55));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: < +3s>, < +20s>, < +p>, < +4d>): <%i>\n", ft_printf("% +3s% +20s% +p.(% +4d)", "65", str, str, 55));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: < +3s>, < +20s>, < +p>, < +4d>): <%i>\n", printf("% +3s% +20s% +p.(% +4d)", "65", str, str, 55));
	printf("********************************************************************************************************\n");
	printf("\ncombination of '+' and '#'\n");
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+#3s>, <+#2s>, <+#p>, <+#4d>): <%i>\n", ft_printf("%+#3s%+#2s%+#p.(%+#4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+#3s>, <+#2s>, <+#p>, <+#4d>): <%i>\n", printf("%+#3s%+#2s%+#p.(%+#4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <#+3s>, <#+2s>, <#+p>, <#+4d>): <%i>\n", ft_printf("%#+3s%#+2s%#+p.(%#+4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <#+3s>, <#+2s>, <#+p>, <#+4d>): <%i>\n", printf("%#+3s%#+2s%#+p.(%#+4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+#3s>, <+#8s>, <+#p>, <+#4d>): <%i>\n", ft_printf("%+#3s%+#8s%+#p.(%+#4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <+#3s>, <+#8s>, <+#p>, <+#4d>): <%i>\n", printf("%+#3s%+#8s%+#p.(%+#4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <#+3s>, <#+8s>, <#+p>, <#+4d>): <%i>\n", ft_printf("%#+3s%#+8s%#+p.(%#+4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <#+3s>, <#+8s>, <#+p>, <#+4d>): <%i>\n", printf("%#+3s%#+8s%#+p.(%#+4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <+#3s>, <+#2s>, <+#p>, <+#4d>): <%i>\n", ft_printf("%+#3s%+#2s%+#p.(%+#4d)", "65", str, str, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <+#3s>, <+#2s>, <+#p>, <+#4d>): <%i>\n", printf("%+#3s%+#2s%+#p.(%+#4d)", "65", str, str, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <#+3s>, <#+2s>, <#+p>, <#+4d>): <%i>\n", ft_printf("%#+3s%#+2s%#+p.(%#+4d)", "65", str, str, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <#+3s>, <#+2s>, <#+p>, <#+4d>): <%i>\n", printf("%#+3s%#+2s%#+p.(%#+4d)", "65", str, str, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <+#3s>, <+#20s>, <+#p>, <+#4d>): <%i>\n", ft_printf("%+#3s%+#20s%+#p.(%+#4d)", "65", str, str, 55));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <+#3s>, <+#20s>, <+#p>, <+#4d>): <%i>\n", printf("%+#3s%+#20s%+#p.(%+#4d)", "65", str, str, 55));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <#+3s>, <#+20s>, <#+p>, <#+4d>): <%i>\n", ft_printf("%#+3s%#+20s%#+p.(%#+4d)", "65", str, str, 55));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <#+3s>, <#+20s>, <#+p>, <#+4d>): <%i>\n", printf("%#+3s%#+20s%#+p.(%#+4d)", "65", str, str, 55));
	printf("********************************************************************************************************\n");
	printf("\ncombination of ' ' and '#'\n");
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < #3s>, < #2s>, < #p>, < #4d>): <%i>\n", ft_printf("% #3s% #2s% #p.(% #4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < #3s>, < #2s>, < #p>, < #4d>): <%i>\n", printf("% #3s% #2s% #p.(% #4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <# 3s>, <# 2s>, <# p>, <# 4d>): <%i>\n", ft_printf("%# 3s%# 2s%# p.(%# 4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <# 3s>, <# 2s>, <# p>, <# 4d>): <%i>\n", printf("%# 3s%# 2s%# p.(%# 4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < #3s>, < #8s>, < #p>, < #4d>): <%i>\n", ft_printf("% #3s% #8s% #p.(% #4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: < #3s>, < #8s>, < #p>, < #4d>): <%i>\n", printf("% #3s% #8s% #p.(% #4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <# 3s>, <# 8s>, <# p>, <# 4d>): <%i>\n", ft_printf("%# 3s%# 8s%# p.(%# 4d)", "65", str, NULL, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <NULL>, d = <0> (flags: <# 3s>, <# 8s>, <# p>, <# 4d>): <%i>\n", printf("%# 3s%# 8s%# p.(%# 4d)", "65", str, NULL, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: < #3s>, < #2s>, < #p>, < #4d>): <%i>\n", ft_printf("% #3s% #2s% #p.(% #4d)", "65", str, str, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: < #3s>, < #2s>, < #p>, < #4d>): <%i>\n", printf("% #3s% #2s% #p.(% #4d)", "65", str, str, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <# 3s>, <# 2s>, <# p>, <# 4d>): <%i>\n", ft_printf("%# 3s%# 2s%# p.(%# 4d)", "65", str, str, 0));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <0> (flags: <# 3s>, <# 2s>, <# p>, <# 4d>): <%i>\n", printf("%# 3s%# 2s%# p.(%# 4d)", "65", str, str, 0));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: < #3s>, < #20s>, < #p>, < #4d>): <%i>\n", ft_printf("% #3s% #20s% #p.(% #4d)", "65", str, str, 55));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: < #3s>, < #20s>, < #p>, < #4d>): <%i>\n", printf("% #3s% #20s% #p.(% #4d)", "65", str, str, 55));
	printf(". res for ft_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <# 3s>, <# 20s>, <# p>, <# 4d>): <%i>\n", ft_printf("%# 3s%# 20s%# p.(%# 4d)", "65", str, str, 55));
	printf(". res for st_printf for s = <65>, s = <hello>, p = <str>, d = <55> (flags: <# 3s>, <# 20s>, <# p>, <# 4d>): <%i>\n", printf("%# 3s%# 20s%# p.(%# 4d)", "65", str, str, 55));
	printf("********************************************************************************************************\n\n");
	printf(". res for ft_printf for s = <65>, p = <NULL>, d = <0> (flags: < 3s>, <%%>, < p>, < 4d>): <%i>\n", ft_printf("% 3shello%%% p.(% 4d)", "65", NULL, 0));
	printf(". res for st_printf for s = <65>, p = <NULL>, d = <0> (flags: < 3s>, <%%>, < p>, < 4d>): <%i>\n", printf("% 3shello%%% p.(% 4d)", "65", NULL, 0));
	*/
	return (0);
}
